const path = require('path');
require('dotenv').config();

module.exports = {
  pipelineVersion: process.env.PIPELINE_VERSION || 'v1',
  groqApiKey: process.env.GROQ_API_KEY,
  groqPrimaryModel: process.env.GROQ_PRIMARY_MODEL || 'openai/gpt-oss-120b',
  groqFallbackModel: process.env.GROQ_FALLBACK_MODEL || 'openai/gpt-oss-20b',
  hfToken: process.env.HF_TOKEN,
  pollinationsApiKey: process.env.POLLINATIONS_API_KEY,
  pexelsApiKey: process.env.PEXELS_API_KEY,
  unsplashAccessKey: process.env.UNSPLASH_ACCESS_KEY,
  slackBotToken: process.env.SLACK_BOT_TOKEN,
  slackChannelId: process.env.SLACK_CHANNEL_ID,
  instagramAccessToken: process.env.INSTAGRAM_ACCESS_TOKEN,
  instagramTokenEncryptionKey: process.env.INSTAGRAM_TOKEN_ENCRYPTION_KEY,
  instagramUserId: process.env.INSTAGRAM_USER_ID,
  instagramUsername: process.env.INSTAGRAM_USERNAME || 'diem.magazine',
  instagramApiVersion: process.env.INSTAGRAM_API_VERSION || 'v23.0',
  instagramFormat: process.env.INSTAGRAM_FORMAT || 'reel',
  publishInstagramStory: process.env.PUBLISH_INSTAGRAM_STORY !== 'false',
  instagramAudioFile: process.env.INSTAGRAM_AUDIO_FILE || '',
  reelDurationPerSlide: parseFloat(process.env.REEL_DURATION_PER_SLIDE || '0'),
  instagramAllowCarouselFallback: process.env.INSTAGRAM_ALLOW_CAROUSEL_FALLBACK !== 'false',
  publishInstagram: process.env.PUBLISH_INSTAGRAM === 'true',
  githubToken: process.env.GITHUB_TOKEN,
  githubRepository: process.env.GITHUB_REPOSITORY,
  githubRunId: process.env.GITHUB_RUN_ID,
  githubSha: process.env.GITHUB_SHA,
  newsRssUrl: process.env.NEWS_RSS_URL || 'https://www.mk.co.kr/rss/30100041/',
  historyFile: process.env.HISTORY_FILE || path.join(__dirname, 'history.json'),
  postsFile: process.env.POSTS_FILE || path.join(__dirname, 'data', 'posts.json'),
  pipelineStateFile: process.env.PIPELINE_STATE_FILE || path.join(__dirname, 'data', 'pipeline-state.json'),
  publicationsRoot: process.env.PUBLICATIONS_ROOT || path.join(__dirname, 'data', 'publications'),
  editorialHistoryFile: process.env.EDITORIAL_HISTORY_FILE || path.join(__dirname, 'data', 'editorial-history.json'),
  instagramTokenFile: process.env.INSTAGRAM_TOKEN_FILE || path.join(__dirname, 'data', 'instagram-token.enc'),
  maxHistoryDays: parseInt(process.env.MAX_HISTORY_DAYS || '7', 10),
  maxDailyPublicationsPerCategory: Math.max(1, parseInt(process.env.MAX_DAILY_PUBLICATIONS_PER_CATEGORY || '3', 10)),
  groqVisionModel: process.env.GROQ_VISION_MODEL || 'qwen/qwen3.6-27b',
};
